console.log("Hello Apple!, I just want to share something special with you although it was hard for me to share it but I will try my best. As you know na gaano ko pinapahalagaan friendship natin. Pero are you sure na gusto mo pa mag proceed? Hindi ko alam pano to sisimulan pero Apple gusto ko maging honest sayo and yes you've captured my thought completely");
console.log("I appreciate na nanjan ka palagi sakin na nakita mo na halosn lahat ng pinag daanan ko. I have to admit that I find you attractive and cute especially as a hardworking person na nakilala ko ")
console.log("I can't stop thinking about you............................................................................................................................................................................")
console.log("YES, I STILL LIKE YOU I MEAN I STILL LOVE YOU AFTER HOW MANY MONTHS NAKO NAKAPAG CONFESS SAYO PERO I TRY MY BEST NAMAN PARA MAPIGILAN NARARAMDAMAN KO SAYO EH KASE AYOKONG MASIRA YUNG FRIENDSHIP NA NABUILD NATIN LALO NA NGAYON NA MAAYOS NA TAYONG DALAWA...")
console.log("wala ng atrasan to ginusto ko to paninindigan ko to")
console.log("I dont want to make you feel uncomfortable pwede mong sabihin sakin na you feel uncomfy around me kase mas prioritize ko yung nararamdaman mo ayokong mailang ka kaya pag di okay sayo pwede naman akong lumayo")
console.log("Apple I don't want to hide it anymore, pero nabago mo ako ikaw yung nag parealised sakin na kailangan ko maging better sa sarili ko at sa mga taong nakakasama ko and isa ka don ikaw yung pinaka main reason bakit ko nilayuan lahat ng mga maling gawain ko")
console.log("hindi ko alam pano to iexplain hindi ako magaling pag dating sa pag labas ng nararamdaman pero gusto kong malaman mo na sincere ako sa lahat ng ginagawa ko for you never pakong nag effort ng ganito sayo lang ako kumilos ng ganito iba ka sa kanila e")
console.log("ikaw yung tipong tao na kayang baguhin yung isang tao kahit wala kang sinasabi or ginagawa ikaw yung taong pinangarap ko...")
console.log("walang araw na hindi naging ikaw i love everything about you Apple....")
console.log("your flaws...")
console.log("your imperfection.....")
console.log("your eyes....")
console.log("personality...")
console.log("and especially your smile that can make my day complete..")
console.log("Everything about you is just perfect (this might be sound cringe or what pero this is how I feel about you Apple hindi ako magaling mag sabi but i can show it to you")
console.log("Hindi mo kailangang mapressure while reading this, hindi kita pinipilit na ibalik yung pag mamahal na binigay ko sayo Apple, I respect your decisions inilabas ko lang ulit dahil mas lumalalim nararamdaman ko sayo")
console.log("Thank you sa nilaan mo na oras para basahin to HAHA and I'm willing harapin kung ano man ang kakahantungan ng bonding nating dalawa")
console.log("hindi parin mag babago pakikitungo ko sayo if you need my help im willing to help and im still your one call away friend.:))")
console.log("-Marthina")